// aun no se utiliza.
export const SHOW_GROUP = "SHOW_GROUP";
export const SHOW_GROUP_SUCCESS = "SHOW_GROUP_SUCCESS";
export const SHOW_GROUP_ERROR = "SHOW_GROUP_ERROR";

export const SHOW_GROUPBYCOMMUNITY = "SHOW_GROUPBYCOMMUNITY";
export const SHOW_GROUPBYCOMMUNITY_SUCCESS = "SHOW_GROUPBYCOMMUNITY_SUCCESS";
export const SHOW_GROUPBYCOMMUNITY_ERROR = "SHOW_GROUPBYCOMMUNITY_ERROR";
